### ISSUE TITLE
🛑 api.nature.io (v2) is down

### ISSUE THREAD

**Issue by natureOffice** [natureOffice-GmbH/upptime#443]
In [`be95eb1`](https://github.com/natureOffice-GmbH/upptime/commit/be95eb14e382dfd64749cde8b167d4d9407e9610
), api.nature.io (v2) (https://api.nature.io/) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by kulturpessimist** [comment]
New domain. nature.io is now direct.ecozoom.app
